name: Application Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: pip install -r application/requirements.txt
    - name: Run tests
      run: python -m unittest discover application/tests
    - name: Build Docker image
      run: docker build -t fraud-detection-app:latest ./application
    - name: Push to ECR
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <account-id>.dkr.ecr.us-east-1.amazonaws.com
        docker tag fraud-detection-app:latest <account-id>.dkr.ecr.us-east-1.amazonaws.com/fraud-detection-app:latest
        docker push <account-id>.dkr.ecr.us-east-1.amazonaws.com/fraud-detection-app:latest
