all:
  children:
    eks_nodes:
      hosts:
        eks_node_1:
          ansible_host: "{{ lookup('env', 'EKS_NODE_1_IP') }}"
        eks_node_2:
          ansible_host: "{{ lookup('env', 'EKS_NODE_2_IP') }}"
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        node_type: eks_worker 