aws:
  region: us-east-1
  access_key: test_access_key
  secret_key: test_secret_key

openai:
  api_key: test_api_key
  api_endpoint: https://api.openai.com/v1/chat/completions

model:
  threshold: 0.8
  batch_size: 32 