name: Update GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'

jobs:
  update-pages:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for GitHub Pages deployment
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper versioning
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || pip install matplotlib seaborn plotly pandas numpy networkx
          
      - name: Generate plots
        run: |
          # Create mock dataiku module if not available
          mkdir -p dataiku
          touch dataiku/__init__.py
          echo "class Dataset: pass" > dataiku/dataset.py
          
          # Generate plots
          python scripts/generate_all_plots.py
          
          # Create docs/assets/images directory if it doesn't exist
          mkdir -p docs/assets/images
          
          # Copy generated plots to docs directory
          cp dataiku/plots/*.png docs/assets/images/
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          commit_message: "Update data quality and governance visualizations"
          force_orphan: true  # Clean up old files 